### ISSUE TITLE
Erode Recursively

### ISSUE THREAD

**Issue by Dale-Black** [JuliaImages/ImageMorphology.jl#120]
Is there any interest in adding an erosion wrapper or even making `erode` recursive?

e.g.

```julia
function erode_mask(img, num_erosions)
	new_img = img
	i = 0
	while i < num_erosions
		new_img = erode(new_img)
		i += 1
	end
	return new_img
end
```

**Comment by Dale-Black** [comment]
I use a version of this function often, so I wouldn't mind submitting a simple PR to add this exact function or to update the original one to take in recursion

**Comment by timholy** [comment]
`for _ in 1:n; img = erode(img); end` seems pretty short, so I am unconvinced that we need a function for this. Especially since one can imagine many targets for this kind of thing (`imfilter_many_times`, ...). If this were something we wanted, it would be better to define it once generically/orthogonally as something like `img = apply(erode, n, img)` ("apply the `erode` function to `n` times to `img`") but that's scarcely any shorter than the explicit `for` loop.

**Comment by Dale-Black** [comment]
That makes sense, it is very simple to implement and I like the one-liner you provided.

**Comment by johnnychen94** [comment]
Note that almost every basic morphology operator has its in-place version, so

```julia
for _ in 1:n
    erode!(img)
end
```

should be generally faster (since it doesn't allocates new memory)
